// Edit challenges here. Keep each id unique and never reuse an id for a different challenge mid-game.
// type: "once" = each team can complete it once, "judge" = judge awards one team, "count" = tally (+/-)
// judgeOnly: only the judge can change the tally
window.CATEGORIES = [
  {id:"street", name:"Street photos", note:"Spot it, shoot it. Most of these happen on the walk between bars.", items:[
    {"id":"street-01","text":"An illegally parked car","note":"Hydrant, crosswalk, bike lane.","points":50,"type":"once"},
    {"id":"street-02","text":"Street sign matching a teammate's first or last name","note":"","points":100,"type":"once"},
    {"id":"street-03","text":"Bodega cat, actually visible","note":"Rumors don't count.","points":100,"type":"once"},
    {"id":"street-04","text":"Team mimicking a public statue or mural","note":"","points":100,"type":"once"},
    {"id":"street-05","text":"Subway performer mid-performance","note":"Tip required.","points":100,"type":"once"},
    {"id":"street-06","text":"Yankees fan and Mets fan (strangers) in the same photo","note":"Visible gear on both.","points":100,"type":"once"},
    {"id":"street-07","text":"Costumed street performer poses with the team","note":"Tip if asked.","points":100,"type":"once"},
    {"id":"street-08","text":"Live rat","note":"Distance is fine. Zoom counts.","points":150,"type":"once"},
    {"id":"street-09","text":"Someone walking a dog in a stroller","note":"","points":150,"type":"once"},
    {"id":"street-10","text":"Team with mounted NYPD horse","note":"Ask the officer first.","points":200,"type":"once"},
  ]},
  {id:"food", name:"Bodegas & food", note:"", items:[
    {"id":"food-01","text":"Eating pizza","note":"","points":50,"type":"once"},
    {"id":"food-02","text":"Street-cart hot dog","note":"","points":50,"type":"once"},
    {"id":"food-03","text":"Black-and-white cookie split four ways","note":"","points":50,"type":"once"},
    {"id":"food-04","text":"Buy a snack none of you recognize from a corner store","note":"Grossest snack gets +100","points":50,"type":"once"},
    {"id":"food-05","text":"Restaurant with a \"C\" grade in the window","note":"","points":150,"type":"once"},
    {"id":"food-06","text":"Buy cheap bodega flowers and give them to a stranger","note":"Photo of the handoff, with their OK.","points":200,"type":"once"},
  ]},
  {id:"bars", name:"Bars", note:"Drink items need just one teammate. Non-alcoholic counts unless a spirit is named. A bar counts toward only one item.", items:[
    {"id":"bars-01","text":"Successfully split the G at a bar with \"Irish\" or \"Tavern\" in the name","note":"","points":50,"type":"once"},
    {"id":"bars-02","text":"Drink a beer brewed in NYC","note":"Can, tap handle or menu as proof.","points":50,"type":"once"},
    {"id":"bars-03","text":"Order a drink with a tiny umbrella","note":"","points":50,"type":"once"},
    {"id":"bars-04","text":"Order a blue or neon-pink cocktail","note":"","points":50,"type":"once"},
    {"id":"bars-05","text":"Weirdest bathroom graffiti","note":"","points":50,"type":"once"},
    {"id":"bars-06","text":"Take a shot with no hands on the glass","note":"On video. Any liquid.","points":50,"type":"once"},
    {"id":"bars-07","text":"Boat race with a group of locals at the bar","note":"","points":100,"type":"once"},
    {"id":"bars-08","text":"Bartender's custom mystery shot","note":"Video of the reveal and toast.","points":100,"type":"once"},
    {"id":"bars-09","text":"A shot of Malort or Fernet","note":"One teammate.","points":100,"type":"once"},
    {"id":"bars-10","text":"Collect coasters from four different bars","note":"One photo of all four.","points":150,"type":"once"},
    {"id":"bars-11","text":"Beat a stranger at pool, darts or Skee-Ball","note":"","points":150,"type":"once"},
    {"id":"bars-12","text":"Whole team in one bar photo booth","note":"","points":150,"type":"once"},
    {"id":"bars-13","text":"Team photo at a speakeasy entrance","note":"Hidden door, phone booth, unmarked stairs.","points":150,"type":"once"},
    {"id":"bars-14","text":"Drink at a bar that opened before 1900","note":"Sign, menu or bartender on video as proof.","points":150,"type":"once"},
    {"id":"bars-15","text":"A stranger buys a teammate a drink","note":"Return the favor.","points":200,"type":"once"},
    {"id":"bars-16","text":"Flaming drink or one served with smoke","note":"","points":200,"type":"once"},
  ]},
  {id:"people", name:"Strangers", note:"If a stranger is the subject, ask first. If they say no, move on.", items:[
    {"id":"people-01","text":"Stranger in an I ♥ NY shirt","note":"","points":50,"type":"once"},
    {"id":"people-02","text":"Stranger takes your team photo while you photograph them doing it","note":"","points":50,"type":"once"},
    {"id":"people-03","text":"Someone with the same first name as a teammate","note":"","points":100,"type":"once"},
    {"id":"people-04","text":"Tourist with an unfolded paper map","note":"","points":150,"type":"once"},
    {"id":"people-05","text":"High-five a cop or firefighter","note":"","points":150,"type":"once"},
    {"id":"people-06","text":"High-five chain with 10 strangers","note":"One continuous video.","points":150,"type":"once"},
    {"id":"people-07","text":"Street musician plays a song you request","note":"Tip required.","points":150,"type":"once"},
    {"id":"people-08","text":"Toast a bachelorette party or group in matching outfits, with a joint photo","note":"","points":150,"type":"once"},
    {"id":"people-09","text":"Someone who shares a teammate's birthday","note":"Their word is enough.","points":200,"type":"once"},
  ]},
  {id:"judge", name:"Judge's call", note:"Winner takes all. Judge reviews at the final bar.", items:[
    {"id":"judge-01","text":"Best tough-guy pose with the fruitiest drink","note":"","points":100,"type":"judge"},
    {"id":"judge-02","text":"Most absurd souvenir bought for under $5","note":"","points":150,"type":"judge"},
    {"id":"judge-03","text":"Stranger who looks most like someone on the other team","note":"","points":200,"type":"judge"},
    {"id":"judge-04","text":"Most quintessentially New York photo of the day","note":"","points":300,"type":"judge"},
  ]},
  {id:"bonus", name:"Bonuses", note:"", items:[
    {"id":"bonus-01","text":"Each bar visited beyond the first three","note":"Tap + for each one.","points":50,"type":"count"},
    {"id":"bonus-02","text":"First team to text the judge a 1,500-point screenshot","note":"","points":150,"type":"judge"},
    {"id":"bonus-03","text":"A stranger joins you for a stop and ends up in 3+ photos","note":"","points":200,"type":"once"},
  ]},
  {id:"pen", name:"Penalties", note:"Tap + each time it happens.", items:[
    {"id":"pen-01","text":"Late to the final bar, per 5 minutes","note":"","points":-50,"type":"count","judgeOnly":true},
    {"id":"pen-02","text":"Cab or rideshare between stops","note":"","points":-100,"type":"count","judgeOnly":true},
  ]},
];
